[
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ac-central-high-school-ashland-il_71631134b2.png",
    school: "A-C Central",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ace-technical-charter-school-chicago-il_674817658e.png",
    school: "ACE",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4638e1f67c_p860.png", school: "Soto" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3f4418a35d_p810.png", school: "ACTC" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/65d0169f5b_p874.png", school: "Abingdon-Avon" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Academy%20for%20the%20Arts&primaryColor=0x0020c2&secondaryColor=0xffffff",
    school: "Aca. for Arts",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3bd10ba693_p514.png", school: "ASA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch092a67a763_p582.png", school: "Sor Juana" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f0114996e0_p474.png", school: "Addison Trail" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/agape-christian-school-marion-il_d7f9600529.png",
    school: "Agape Christian",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/agricultural-science-high-school-chicago-il_ceec3563e5.png",
    school: "Agri. Science",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/air-force-academy-chicago-il_267d15e859.png", school: "Air Force" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/al-raby-school-for-community-and-environment-chicago-il_55855d5a11.png",
    school: "Al Raby",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/alwood-high-school-woodhull-il_f2973659de.png", school: "AlWood" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/alcott-college-preparatory-chicago-il_72bc884d7e.png",
    school: "Alcott",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aldenhebron-high-school-hebron-il_c7b0d531bc.png",
    school: "Alden-Hebron",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/alleman-high-school-rock-island-il_bae6435a69.png", school: "Alleman" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/altamont-high-school-altamont-il_8da279f9d0.png", school: "Altamont" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dc1ed58fd7_p434.png", school: "Fairfield" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Faith%20Lutheran%20High%20School&primaryColor=0xff0000&secondaryColor=0x000000",
    school: "Faith Lutheran",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d168cd60c9_p143.png", school: "Farmington C." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b3f6b9ceda_p812.png", school: "Farragut" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aea84b85f0_p453.png", school: "Father McGivney" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b2ade1eeaf_p359.png", school: "Fenger" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c274679b50_p185.png", school: "Fenton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fenwick-high-school-oak-park-il_87c0eacf16.png", school: "Fenwick" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4784bef266_p405.png", school: "Fieldcrest" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/218f1e2071_p772.png", school: "First Baptist" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/477bb7356e_p739.png", school: "Fisher" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9544173f68_p705.png", school: "FCHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/76cde24185_p142.png", school: "Flora" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7bf272fe71_p123.png", school: "Foreman" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4071ab951d_p559.png", school: "Forreston" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3798e6b838_p599.png", school: "FVLA" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fw-parker-high-school-chicago-il_f1ef3f8c70.png",
    school: "Francis Parker",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/douglas-macarthur-high-school-decatur-il_5b78a33194.png",
    school: "MacArthur",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/macomb-high-school-macomb-il_098407a054.png", school: "Macomb" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/38727da539_p406.png", school: "Madison" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7ebab9b423_p374.png", school: "Mahomet-Seymour" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2a03ea8382_p536.png", school: "Maine East" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/maine-south-high-school-park-ridge-il_8973f35c44.png",
    school: "Maine South",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/013b5a862d_p602.png", school: "Maine West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/manley-high-school-chicago-il_9f78d5f782.png", school: "Manley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/77854bea0a_p627.png", school: "Mansueto" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f725f36b95_p269.png", school: "Manteno" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/79a990d9f8_p227.png", school: "Manual" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/be7aeb9bbe_p712.png", school: "Marengo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3c91ffe45e_p946.png", school: "Marian Catholic" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/957eb8a5ce_p204.png", school: "Marian Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4b150610d8_p825.png", school: "Marine" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ac7763b127_p648.png", school: "Marion" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c21e046a4b_p970.png", school: "Marissa" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8a7c211efb_p161.png", school: "Marist" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rowva-high-school-oneida-il_1d31fea13c.png", school: "ROWVA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch2ab9042f3d_p4.png", school: "RW Cougars" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ramsey-high-school-ramsey-il_fc3f9203a9.png", school: "Ramsey" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b0d545aa3a_p451.png", school: "Rantoul" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rauner-college-prep-high-school-chicago-il_6d5bafa1c6.png",
    school: "Rauner",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/reavis-high-school-burbank-il_d7085cd0a7.png", school: "Reavis" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/534ad251d7_p882.png", school: "Red Bud" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/red-hill-high-school-bridgeport-il_a7009a3a5c.png",
    school: "Red Hill",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/reedcuster-high-school-braidwood-il_c2219f2a86.png",
    school: "Reed-Custer",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/regina-dominican-high-school-wilmette-il_0b6ddbbbfa.png",
    school: "RDHS",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/resurrection-high-school-chicago-il_1504c32d81.png",
    school: "Resurrection",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rich-central-high-school-olympia-fields-il_e8fa5dd8aa.png",
    school: "Rich Central",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/634db4e4bd_p149.png", school: "Rich East" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rich-south-high-school-richton-park-il_71b60c2b5d.png",
    school: "Rich South",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/65671d906d_p465.png", school: "Richards" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4908eb9ae9_p632.png", school: "Richland" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/richmondburton-high-school-richmond-il_8a62585f46.png",
    school: "Richmond-Burton",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f03c690017_p834.png", school: "Waldorf" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/walter-payton-college-prep-high-school-chicago-il_48a5fdaa90.png",
    school: "Payton",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9f096216c5_p118.png", school: "Walther Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d673865082_p702.png", school: "Waltonville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/651b488f6c_p373.png", school: "Warren" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/warren-high-school-gurnee-gurnee-il_9838b4e54f.png", school: "WTHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/219960378f_p448.png", school: "W'burg-Latham" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a9994e21c0_p641.png", school: "Warsaw" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schf129becd53_p806.png", school: "Washington Cent" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0f09512f72_p552.png", school: "Washington" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/afcb9ea347_p768.png", school: "Chicago" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c3947f2a97_p351.png", school: "Waterloo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9bbd28c25d_p98.png", school: "Watseka" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9a201ec860_p549.png", school: "Waubonsie Vly." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/29234cfc6b_p464.png", school: "Wauconda" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/763ca3b411_p30.png", school: "Waukegan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d4af595469_p184.png", school: "Waverly" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7f11c878a5_p585.png", school: "Althoff" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7eb3389a4b_p547.png", school: "Alton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9300ece5dd_p715.png", school: "Amandla Charter" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/amboy-high-school-amboy-il_c90a8dd053.png", school: "Amboy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch8a99c7d5cb_p367.png", school: "Amboy JHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch5ea88a6b29_p506.png", school: "Amer Dream STEM" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/amundsen-high-school-chicago-il_561bc1f3bc.png", school: "Amundsen" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bec40d177a_p72.png", school: "Andrew" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/82fd3e7e6f_p405.png", school: "Anna-Jonesboro" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/annawan-high-school-annawan-il_2f21fb083b.png", school: "Annawan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e8b73c2b2e_p481.png", school: "Antioch" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aqsa-high-school-bridgeview-il_264563e554.png", school: "Aqsa" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c107e8a31a_p968.png", school: "Aquin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2a75242b98_p552.png", school: "Arcola" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/29487c3dad_p881.png", school: "Argenta-Oreana" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/argo-community-high-school-summit-il_8edd3b1967.png", school: "Argo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/749b333bfd_p976.png", school: "Ariel" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/94f37d5336_p813.png", school: "Armstrong" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bbbaf1266e_p678.png", school: "Arthur Chr." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/arthurlovingtonatwoodhammond-high-school-arthur-il_3e838f93b6.png",
    school: "ALAH",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ashtonfranklin-center-high-school-ashton-il_f87df0be80.png",
    school: "Ashton-Franklin",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8d8b839594_p400.png", school: "AECHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4ee549260f_p523.png", school: "Astoria" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dc7b56f018_p33.png", school: "Athens" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/328ca24403_p183.png", school: "Atwood-Hammond" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2d4106261c_p587.png", school: "Auburn" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/17eb0bfcf9_p597.png", school: "Central Cath." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_aurorachristian.png", school: "Aurora Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/814cd27418_p364.png", school: "West Aurora" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1578ee9dda_p795.png", school: "ABEA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7cb7b0e549_p314.png", school: "Austin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a1e19480af_p885.png", school: "Avon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/049a99c378_p760.png", school: "BOYCP" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6a5d9c5a08_p348.png", school: "Barrington" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ec5d06da8_p395.png", school: "Bartlett" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/89881bfb3e_p187.png", school: "Batavia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sche2fb092c52_p373.png", school: "Beacon Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e77e05c0f1_p532.png", school: "Beardstown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a98d697e2b_p644.png", school: "Beecher City" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7667b1b06b_p855.png", school: "Beecher" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/38e01ed740_p652.png", school: "Belleville East" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/belleville-west-high-school-belleville-il_ef07e9b513.png",
    school: "Belleville West",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/306d0b375f_p793.png", school: "Belvidere" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9cfa079572_p553.png", school: "Belvidere North" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d6b6fa6d3c_p49.png", school: "Bement" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5c7f638693_p126.png", school: "Benet Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1200f109ab_p175.png", school: "Benton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7ee0557ab6_p331.png", school: "Berean Baptist" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Bernard%20Zell%20Anshe%20Emet&primaryColor=&secondaryColor=",
    school: "BZAE",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/77fac952f1_p89.png", school: "Bethel Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3101928c1e_p90.png", school: "Bishop McNamara" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8ed57e295e_p302.png", school: "BHRA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3f61a11eb5_p400.png", school: "Bloom" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fc5cddec52_p827.png", school: "Bloomington" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fc4579dcae_p642.png", school: "Blue Ridge" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/62f3f76f82_p441.png", school: "Bluffs" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1c7b876279_p341.png", school: "Bogan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/35ab609f32_p807.png", school: "Bolingbrook" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d89bc6d446_p73.png", school: "Bowen" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ce1a76c30_p76.png", school: "Boylan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ca1905529e_p139.png", school: "Bradley-Bour." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8bf3a0f34d_p831.png", school: "Brehm" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4eb3510572_p475.png", school: "Bremen" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1ed45443b4_p311.png", school: "Brentwood Bap." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/brimfield-high-school-brimfield-il_08de8e1998.png",
    school: "Brimfield",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/91f12cc828_p652.png", school: "BISC of CLP" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch4158f2b551_p438.png", school: "Brookwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/472148f3db_p406.png", school: "Brother Rice" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4973dce3f5_p861.png", school: "Brown County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c9c9b9d5df_p194.png", school: "Brownstown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e3911bd09f_p519.png", school: "Brussels" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b6cb99c180_p305.png", school: "Buffalo Grove" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fbc6fd5e9a_p397.png", school: "Bunker Hill" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/02207cd29d_p909.png", school: "Bureau Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ef055da1a4_p574.png", school: "BPCHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8c064264ef_p778.png", school: "Noble-Butler" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a3aba22a1f_p514.png", school: "Byron" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/198e13f771_p599.png", school: "CICS Ellison" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9633ac26c6_p541.png", school: "Cahokia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f525484197_p768.png", school: "Cairo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d9727aa4e9_p24.png", school: "Calhoun" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e3cd599281_p242.png", school: "Calvary" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/55cde5c5aa_p745.png", school: "Calvary Baptist" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d1df92bdb9_p535.png", school: "Cambridge" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/90a68e7b4e_p586.png", school: "Canton" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/carbondale-community-high-school-carbondale-il_1f887778fc.png",
    school: "Carbondale",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_sandburg.png", school: "Sandburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d3cc524273_p458.png", school: "Carlinville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9dc26c1cfb_p914.png", school: "Carlyle" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/carmel-catholic-high-school-mundelein-il_2c4eec5890.png",
    school: "Carmel",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/41c8f96d63_p294.png", school: "Carmi-White Co." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3454673add_p278.png", school: "Carrier Mills" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Carroll%20Catholic%20School&primaryColor=&secondaryColor=", school: "CCS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c3e21ba655_p148.png", school: "Carrollton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/57ccf22e55_p715.png", school: "Carterville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6d2ef3369f_p4.png", school: "Carver" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d1be8de92e_p672.png", school: "Cary Grove" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/caseywestfield-high-school-casey-il_3396d42d39.png",
    school: "Casey-Westfield",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/29c40b1e41_p965.png", school: "Catalyst Maria" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ac28c89acb_p926.png", school: "Catlin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_centennial.png", school: "Centennial" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fe5cfbbbfc_p656.png", school: "Central A & M" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c88d391124_p773.png", school: "Central Breese" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/central-high-school-burlington-burlington-il_029f04cefb.png",
    school: "Burlington",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5530f03d03_p18.png", school: "Camp Point" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/61c60829f6_p860.png", school: "Central Clifton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/82be2727dc_p640.png", school: "Centralia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/906dad9250_p788.png", school: "Century" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/261ec8f2b0_p654.png", school: "Cerro Gordo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a637359704_p724.png", school: "Milledgeville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/37ea045f39_p925.png", school: "Champaign C." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5eeed767c0_p441.png", school: "Charleston" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/72a9bfea97_p464.png", school: "Chester" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Chester-East%20Lincoln&primaryColor=&secondaryColor=",
    school: "Chester East",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bbb96c3bb5_p155.png", school: "Chicago Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/927327a64d_p423.png", school: "CBA" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/chicago-christian-high-school-palos-heights-il_4b523f43e8.png",
    school: "Chicago Chr.",
  },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Chicago%20City%20Day%20School&primaryColor=&secondaryColor=",
    school: "CCDS",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ba29e5786a_p728.png", school: "Chi. Hope Aca." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/263466c767_p815.png", school: "ChicagoQuest" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/169e7dd8ca_p796.png", school: "CICS Longwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/448ed4d85e_p936.png", school: "CICS Northtown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3b5142869a_p573.png", school: "CMSA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/83e7d6a53a_p849.png", school: "Chicago Mil." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sche3c449ae91_p801.png", school: "Chicago PS" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Chicago%20Talent%20Development%20High%20School&primaryColor=0xcc2233&secondaryColor=0xffd700",
    school: "Chicago Talent",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b1b3775541_p657.png", school: "Chicago Tech" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schc5f7018117_p451.png", school: "TIlden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/484c7675de_p436.png", school: "Chicago Voc." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_cjhs.png", school: "C'land Jewish" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3893cf61c4_p415.png", school: "Chrisman" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3e2564ac67_p970.png", school: "Christ Lutheran" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1821927072_p931.png", school: "Christ Our Rock" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1413bd6803_p976.png", school: "COSL" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/54b0985ee6_p16.png", school: "Christ the King" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/16161c60e3_p983.png", school: "Chr. Fellow." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7da2c16c38_p847.png", school: "Chr. Heritage" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fc57bd97cc_p447.png", school: "Chr. Liberty" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ecd9e6343d_p32.png", school: "Christian Life" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/765bdf7323_p692.png", school: "Christopher" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a279c3c53e_p657.png", school: "Cisne" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fc9173b4f2_p458.png", school: "Cissna Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/975ad90b20_p680.png", school: "Civic Memorial" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a610c0ca6c_p943.png", school: "Clay City" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e29dc63e26_p734.png", school: "Clinton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/87c1e5d0a3_p447.png", school: "Coal City" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aed9a4c06f_p140.png", school: "Cobden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schdf56b9a0bc_p859.png", school: "College Prep" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/46f86cf149_p873.png", school: "Collins Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f82a7a1ddd_p808.png", school: "Collinsville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/02039ccb54_p647.png", school: "Columbia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e62881ddb3_p979.png", school: "D99" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4c22496997_p700.png", school: "Community West" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/james-b-conant-high-school-hoffman-estates-il_9cf0b1efac.png",
    school: "Conant",
  },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Concordia%20Lutheran%20School&primaryColor=0x8b2331&secondaryColor=0xfbbc15",
    school: "Concordia",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fa081ade99_p923.png", school: "Corliss" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cornerstone-christian-academy-bloomington-il_33c259522c.png",
    school: "Cornerstone",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch6aee266b7b_p369.png", school: "Corpus Christi" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/33c7f62bfd_p682.png", school: "Coulterville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3a41c9e9ee_p506.png", school: "Cowden-Herrick" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/540ed87949_p544.png", school: "Crab Orchard" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/35ed0bac82_p6.png", school: "Crane" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/22c81d04d5_p494.png", school: "Crete-Monee" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e6eea538db_p912.png", school: "Cristo Rey" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c6be3d6f71_p514.png", school: "CRSM" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0de88493da_p146.png", school: "Crossroads Area" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c9e14d9a65_p903.png", school: "CCA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/88a5cc45dd_p758.png", school: "Crystal Lake" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/64a3217e61_p383.png", school: "Crystal Lake S." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/03b5863aa9_p890.png", school: "Cuba" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cumberland-high-school-teledo-il_1ea1354079.png",
    school: "Cumberland",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/22ead0ec67_p13.png", school: "Curie" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/423cf546ec_p576.png", school: "NCDRWT" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/578b641a6d_p766.png", school: "Dakota" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/baf064abb2_p175.png", school: "Danville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/652b4602e3_p176.png", school: "DeLaSalle" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f6e8113ab5_p530.png", school: "DeKalb" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4e4a91018a_p211.png", school: "DeLand-Weldon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c898b615a1_p139.png", school: "DePaul" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b3e7fb192a_p80.png", school: "DePue" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=DeVry%20Advantage%20Academy&primaryColor=&secondaryColor=",
    school: "DeVry Advantage",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cce6edf79c_p163.png", school: "Decatur Chr." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/deer-creekmackinaw-high-school-mackinaw-il_b0a4fc1142.png",
    school: "DCMHS",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/deerfield-high-school-deerfield-il_fc877aa43e.png",
    school: "Deerfield",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2ed66e75ca_p778.png", school: "Delavan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/362caca32c_p515.png", school: "Dieterich" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/14ad46f7c0_p100.png", school: "Disney II" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dixon-high-school-dixon-il_b7602cdca3.png", school: "Dixon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/42f7fe26f5_p63.png", school: "Dongola" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aa74da4d70_p357.png", school: "Donovan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/76f79dc326_p166.png", school: "DGN" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4dd30fa065_p204.png", school: "DGS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7507f7c44d_p558.png", school: "DuQuoin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/619f7c9858_p967.png", school: "DuSable" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6add141b66_p135.png", school: "Dunbar" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a04dc4b424_p667.png", school: "Dundee-Crown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/39f2419636_p505.png", school: "Dunlap" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sche61a83aa66_p607.png", school: "Dunlap Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d6e4c6b6cc_p697.png", school: "Dupo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/durand-high-school-durand-il_a5d9a9d2d1.png", school: "Durand" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/85d168828b_p854.png", school: "Dwight" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f7d5a0bcca_p505.png", school: "Dyett" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f3ed191167_p588.png", school: "Earlville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch9364268291_p330.png", school: "Earlville JHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5cd5f2ec59_p87.png", school: "East Alton-Wood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a6a477ef35_p984.png", school: "East Aurora" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b3a1bf05dd_p201.png", school: "East Dubuque" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4ab22bec3a_p991.png", school: "East Leyden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8811a24855_p369.png", school: "East Moline" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/146fde1848_p370.png", school: "East Peoria" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=East%20St%20Louis%20Lincoln&primaryColor=&secondaryColor=",
    school: "Lincoln",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ed9f0a7e6_p597.png", school: "East St. Louis" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/48f5a052bc_p964.png", school: "Eastland" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/76fa1e1c35_p524.png", school: "Edinburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/05a8c173dc_p782.png", school: "Edwards County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4027e3c833_p881.png", school: "Edwardsville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dd00f3e429_p396.png", school: "Effingham" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/81c6a1eaa2_p417.png", school: "Egyptian" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9b18560de2_p568.png", school: "Eisenhower" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/254ae8bd58_p586.png", school: "EPG" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d806be8e62_p886.png", school: "Eldorado" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c7d0840c06_p667.png", school: "Elgin Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5e1098014a_p127.png", school: "Elgin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/40ae13c24f_p616.png", school: "Elk Grove" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cb33cdf782_p514.png", school: "Elmwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/be2e4579d8_p530.png", school: "Elmwood Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f6bba75229_p393.png", school: "Elverado" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f752d2e9a5_p110.png", school: "Epic" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Epiphany%20School&primaryColor=&secondaryColor=",
    school: "Epiphany School",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/da360369bc_p948.png", school: "EP COOP" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8c5694fe32_p914.png", school: "Eureka" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aff92fd52f_p190.png", school: "Evanston" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3bf004f878_p948.png", school: "Evergreen Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d2fb308a66_p111.png", school: "Frankfort" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/012a389180_p53.png", school: "Franklin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/62aba1efaa_p438.png", school: "Douglass    " },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/af9c71d416_p68.png", school: "Freeburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2c795b5a92_p255.png", school: "Freeport" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7b98e48d41_p250.png", school: "Fremd" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/63dc53b585_p546.png", school: "Ft. Bowman Aca." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2546779fd7_p12.png", school: "Fulton" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=GEMS%20World%20Academy&primaryColor=&secondaryColor=", school: "GEM" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c450c6234d_p514.png", school: "Gage Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aacbc89b89_p242.png", school: "Galatia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/296b188a48_p712.png", school: "Galena" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5e59edb7c8_p363.png", school: "Galesburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c07e553967_p222.png", school: "Gallatin County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/799c91813c_p330.png", school: "Galva" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/570652ad2c_p753.png", school: "GSW" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cd2e157cc6_p726.png", school: "Gateway" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/geneseo-high-school-geneseo-il_085674ccb7.png", school: "Geneseo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/55384794d9_p490.png", school: "Geneva" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e740a4207d_p214.png", school: "Genoa-Kingston" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5b45870563_p673.png", school: "G-R" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fcb707158a_p146.png", school: "Gibault" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/674e0220cb_p186.png", school: "GCMS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/476b8fada9_p776.png", school: "Gillespie" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a49942057b_p645.png", school: "Glenbard East" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5ea5ea4360_p302.png", school: "Glenbard North" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1bc4c2c0f8_p501.png", school: "Glenbard South" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/glenbard-west-high-school-glen-ellyn-il_b9ef024c73.png",
    school: "Glenbard West",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/glenbrook-north-high-school-northbrook-il_6bdc292c61.png",
    school: "Glenbrook North",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c3c9137e8a064860bd3257655c44d1f9.png", school: "Glenbrook South" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b94456c9a9_p841.png", school: "Glenwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/golder-prep-high-school-chicago-il_817c1919b3.png", school: "Golder" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/96cb2a8dde_p402.png", school: "Goreville" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/governor-french-academy-belleville-il_33c159599d.png",
    school: "Governor French",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/grace-baptist-academy-kankakee-il_2d69f3fe25.png",
    school: "Grace Christian",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/granite-city-high-school-granite-city-il_5312f4e108.png",
    school: "Granite City",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4e87d92e9c_p773.png", school: "Grant" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5096f92fd9_p239.png", school: "Grant Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/75cdd08053_p995.png", school: "Grayslake C." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/grayslake-north-high-school-grayslake-il_13f5f0cbfd.png",
    school: "Grayslake North",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b9a649debd_p681.png", school: "Grayville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f9586f7fce_p38.png", school: "Greenfield" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/greenview-high-school-greenview-il_33a76eff4c.png",
    school: "Greenview",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b08a7315a8_p917.png", school: "Greenville" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/griggsvilleperry-high-school-griggsville-il_32811cc640.png",
    school: "G'ville-Perry",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dd986b5381_p772.png", school: "Guilford" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1b34a9c07e_p558.png", school: "Brooks" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8c37cb6c10_p70.png", school: "Jacobs" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4b1d81b67_p460.png", school: "HRK" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hales-franciscan-high-school-chicago-il_279949c760.png",
    school: "HFHS",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hall-high-school-spring-valley-il_a0c0986463.png", school: "Hall" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hamilton-county-high-school-mcleansboro-il_d0c689307b.png",
    school: "Hamilton County",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/13868fea24_p512.png", school: "Hamilton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/40217ab891_p680.png", school: "Hampshire" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hancock-high-school-chicago-il_4154105f30.png", school: "Hancock" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/18e06b791c_p819.png", school: "Hansberry" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hardin-county-high-school-elizabethtown-il_75012b2f1f.png",
    school: "Hardin County",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/john-marshall-harlan-high-school-chicago-il_57c1447d83.png",
    school: "Harlan",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7085891a86_p11.png", school: "Harlem" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/harper-high-school-chicago-il_31e1c09eda.png", school: "Harper" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/harrisburg-high-school-harrisburg-il_5eede5d2b0.png",
    school: "Harrisburg",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7183237e90_p741.png", school: "Hartsburg-Emden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/harvard-high-school-harvard-il_5d49c333de.png", school: "Harvard" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ac3c1a5417_p944.png", school: "Harvest Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d60af513af_p996.png", school: "Havana" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/de2b011b56_p279.png", school: "Helping Hand" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/henrysenachwine-l-henry-il_2d5af6acdc.png", school: "HSHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch944e79e08a_p728.png", school: "Herget" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/heritage-high-school-broadlands-il_a190bd529f.png",
    school: "Heritage",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ca02f8879c_p421.png", school: "Herrin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2498dc92e8_p317.png", school: "Herscher" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e287b95f14_p31.png", school: "Hersey" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4629ed0cb4_p799.png", school: "Heyworth" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hiawatha-high-school-kirkland-il_8d2efe5d35.png", school: "Hiawatha" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6dd733ee91_p272.png", school: "Highland" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/highland-park-high-school-highland-park-il_8fca70e17e.png",
    school: "Highland Park",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hillcrest-high-school-country-club-hills-il_78e53c8abd.png",
    school: "Hillcrest",
  },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Hillel%20Torah&primaryColor=&secondaryColor=", school: "Hillel Torah" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aa33a7d879_p966.png", school: "Hillsboro" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hinckleybig-rock-high-school-hinckley-il_538cd7f158.png",
    school: "HBR",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch83c9daedfd_p500.png", school: "HBRMS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/33ae2b79d1_p457.png", school: "Hinsdale Adv." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hinsdale-central-high-school-hinsdale-il_9a6a629555.png",
    school: "Hinsdale Cen.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/799111b214_p631.png", school: "Hinsdale South" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a3fac33bcc_p278.png", school: "Hirsch" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/hoffman-estates-high-school-hoffman-estates-il_ca374cb161.png",
    school: "Hoffman Estates",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/scha73830070f_p493.png", school: "Holy Angels" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/scha460f97ce1_p717.png", school: "Holy Cross" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/holy-trinity-high-school-chicago-il_04e7272394.png",
    school: "Holy Trinity",
  },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Home%20School%20Resource%20Center&primaryColor=&secondaryColor=",
    school: "HSRC",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/69f03bedcd_p482.png", school: "Hononegah Comm." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/efcd636a6f_p211.png", school: "Hoopeston Area" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cac6d2600a_p722.png", school: "Hope" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4b9de0eeb_p797.png", school: "HSA Charter" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8365cf9fb7_p955.png", school: "HSA Southwest" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Horizon%20Sciences%20Academy&primaryColor=&secondaryColor=",
    school: "HSA",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3feec46856_p996.png", school: "Hubbard" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8886cb51f3_p563.png", school: "Huntley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_hutsonville.png", school: "Hutsonville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/61dc7a626e_p952.png", school: "Hyde Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7c708305b1_p13.png", school: "IC Catholic" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch5f5329acfe_p314.png", school: "IHSA Schools" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/itw-david-speer-academy-chicago-il_e5f5e3b7d9.png",
    school: "ITW David Speer",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e25381393f_p779.png", school: "Ida Crown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/714b8415f3_p26.png", school: "Illiana Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fa0d8c21cb_p627.png", school: "Illini Bluffs" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/19aaf1b26a_p657.png", school: "Illini Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9567d3a540_p771.png", school: "Illini West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4989ee78da_p985.png", school: "IHSA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b41af3f02c_p645.png", school: "Illinois Luth." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0c2955ab19_p979.png", school: "IMSA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5c3015be95_p312.png", school: "ISD" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/64069d2ef3_p432.png", school: "ISVI" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ad4dda098d_p154.png", school: "Illinois Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a0e1481f8b_p406.png", school: "Indian Creek" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4b35b91be7_p540.png", school: "IHSCA" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Interstate%208&primaryColor=&secondaryColor=", school: "Interstate 8" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ebb442b0c_p12.png", school: "Intrinsic Char." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/989d7e51c0_p64.png", school: "Iroquois West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bbc2c2f7bc_p449.png", school: "IFS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0867f1d731_p860.png", school: "Morton - Cicero" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8f7919c2b1_p397.png", school: "Jacksonville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5938644756_p63.png", school: "Jamaica" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/50b97f0c7e_p94.png", school: "Jefferson" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e46a180908_p254.png", school: "Jersey" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch8a06c03665_p791.png", school: "Jewel" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/73d52d03b2_p862.png", school: "Kennedy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e0238d016f_p331.png", school: "John Hope" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/704eee6872_p702.png", school: "Johnsburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/879231a5a8_p470.png", school: "Johnson Prep" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/91775e0f56_p992.png", school: "Johnston City" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/joliet-catholic-academy-joliet-il_1012e00a3d.png",
    school: "Joliet Cath.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/38d54b9f16_p251.png", school: "Joliet Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1db4ab1eb8_p552.png", school: "Joliet West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ca1e69e7c3_p479.png", school: "Jones" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7e9ea25c35_p882.png", school: "JMG" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a786c90694_p858.png", school: "Josephinum" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4b4a46e0e_p857.png", school: "Juarez" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/69704e9cbd_p707.png", school: "Judah Christian" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/percy-julian-high-school-chicago-il_3aced2e58b.png", school: "Julian" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Juniors&primaryColor=&secondaryColor=", school: "Juniors" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b751ed25d3_p162.png", school: "Kaneland" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3c1bea0fed_p991.png", school: "Kankakee" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e9a4ce6c88_p856.png", school: "Oakland" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/162992861c_p849.png", school: "Kansas" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/257ab17121_p769.png", school: "Keith Co. Day" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_chicago-kelly.png", school: "Kelly" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4b97322033_p430.png", school: "Kelvyn Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/081853b101_p199.png", school: "Kenwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/498781bdf7_p155.png", school: "Kewanee" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d0dfe3517b_p6.png", school: "King" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c077dbf802_p348.png", school: "Knoxville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dce3dd3dc4_p530.png", school: "LaMoille" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/213eace7bf_p852.png", school: "LaSalle-Peru" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/455bc9e3ff_p434.png", school: "Lake Co. Bap." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4baf4f0f63_p614.png", school: "LFA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6aea66b8e7_p932.png", school: "Lake Forest" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/69b5303676_p289.png", school: "Lake Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d23ff150b0_p311.png", school: "Lake View" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b231d8f1bd_p219.png", school: "Lake Zurich" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/50bbe2f602_p237.png", school: "Lakes" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a5092870f6_p75.png", school: "Lane Tech" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fe28e7b9c4_p549.png", school: "Lanphier" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/653149c748_p372.png", school: "Larkin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9cbc05bf67_p337.png", school: "LSC" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2458930b8c_p898.png", school: "Lawrence Hall" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a186ae6535_p335.png", school: "Lawrenceville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/96f2027dda_p275.png", school: "LeRoy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5476daa78b_p713.png", school: "Lebanon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/359d00f4d7_p394.png", school: "LPCA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ee560ddd8_p861.png", school: "Leland" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch5133c5ae35_p995.png", school: "Leland JR" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cbcf08ba53_p308.png", school: "Lemont" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ce922e3a66_p868.png", school: "Lena-Winslow" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/68b476d578_p77.png", school: "Leo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cf255ab167_p467.png", school: "Lewistown" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dbc89c9124_p0.png", school: "Lexington" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b868fa7457_p379.png", school: "Leyden Twp." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3508d0dad9_p705.png", school: "Liberty" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1f8b40038c_p831.png", school: "Libertyville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1fd79359e3_p611.png", school: "Limestone" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Lincoln%20Magnet%20School&primaryColor=&secondaryColor=",
    school: "Lincoln Magnet",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c935dd3f7f_p531.png", school: "Lincoln Park" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/lincolnway-central-high-school-new-lenox-il_dfca101367.png",
    school: "Lincoln-Way C.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch066a229554_p489.png", school: "District 210" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/13700086cb_p817.png", school: "Lincoln-Way E." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/lincolnway-north-high-school-frankfort-il_9195925c21.png",
    school: "Lincoln-Way N.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/68401fc21c_p576.png", school: "Lincoln-Way W." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1df36be727_p671.png", school: "Lincolnwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/07ab013c24_p501.png", school: "Lindblom" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schb2b8564f97_p109.png", school: "Lisbon JR" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ae36040adb_p212.png", school: "Lisle" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/649aad82ad_p686.png", school: "Litchfield" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3252ba59a1_p520.png", school: "LBPAA" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Little%20Ten&primaryColor=&secondaryColor=", school: "Little Ten" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/317eb4d5b5_p563.png", school: "Little Village" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7c6757ab1f_p904.png", school: "Lockport Twp." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f5a2d16e4c_p422.png", school: "Lovejoy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/569dbe78a7_p134.png", school: "LWHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f3dd33fadc_p430.png", school: "Loyola" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2d0ec1401e_p657.png", school: "Luther East" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/luther-north-college-prep-chicago-il_89bc5f53db.png",
    school: "Luther North",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/00a0a62ede_p484.png", school: "Springfield" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ae78a0d301_p80.png", school: "Lutheran" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bc25d5cf5e_p4.png", school: "Lycee Francais" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/59300575f8_p650.png", school: "Lyons Twp." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dce429c286_p329.png", school: "Marmion Academy" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/maroaforsyth-high-school-maroa-il_4c48160a46.png",
    school: "Maroa-Forsyth",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a235455101_p101.png", school: "Marquette Alton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/80c9e7dec0_p468.png", school: "Ottawa" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aa6271a259_p436.png", school: "Marquette Manor" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/07482d3c80_p922.png", school: "Marshall" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a90138ca23_p364.png", school: "Martinsville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sche86f5f87d5_p767.png", school: "MCS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b3a7335d37_p147.png", school: "Mascoutah" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/affb53b55e_p585.png", school: "Massac County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dcc7208c5c_p76.png", school: "Mater Dei" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a2449679d8_p502.png", school: "Mather" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/mattoon-high-school-mattoon-il_ded90937a0.png", school: "Mattoon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4700ee010a_p825.png", school: "McHenry" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ef61f3db62_p821.png", school: "Mendota" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f7729c866a_p503.png", school: "Mercer County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/69bfabc73e_p844.png", school: "MCHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/320e5342e0_p364.png", school: "Meridian Macon" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/meridian-high-school-mounds-mounds-il_d10966d546.png",
    school: "Meridian Mounds",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dd44cb76d4_p241.png", school: "Metamora" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/metea-valley-high-school-aurora-il_a66d77f21d.png",
    school: "Metea Valley",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f330ca8951_p740.png", school: "MELHS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3c0c4a188d_p883.png", school: "Clark" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b13867117e_p775.png", school: "MAP" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schf1c32b9333_p167.png", school: "Midland" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/65fe8bff38_p851.png", school: "Midwest Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c8dc554ab9_p18.png", school: "Milford" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schbb9ecda567_p664.png", school: "Millbrook Jr" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/206de7c679_p357.png", school: "Minooka" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/429bca40a3_p662.png", school: "MVCS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9e598f0572_p367.png", school: "Moline" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/80928e6414_p601.png", school: "Momence" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_monmouthroseville.png", school: "M'mouth-R'ville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8f2646fe68_p591.png", school: "Monticello" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c113d0d7d5_p429.png", school: "Montini" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_mooseheart.png", school: "Mooseheart" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a5e44dc0d7_p368.png", school: "MPA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9ebace5047_p396.png", school: "Morgan Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/744a527118_p733.png", school: "Morris" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a67aee04cc_p422.png", school: "Morrison" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a13514e5c9_p228.png", school: "Morrisonville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5cbd10860d_p515.png", school: "Morton" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Mossville%20Jr%20High&primaryColor=&secondaryColor=",
    school: "Mossville Jr",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dc20ee421d_p254.png", school: "Mother McAuley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/363e677a7f_p397.png", school: "Mt. Carmel" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/99a4b6fe11_p430.png", school: "Mount Vernon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e917d1c8d3_p868.png", school: "Mt. Assisi Aca." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5b215d5d08_p84.png", school: "Mount Carmel" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/05681cee64_p971.png", school: "Mt. Olive" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/758fd85d4d_p363.png", school: "Mt. Pulaski" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ca9ef7e6e6_p985.png", school: "Mt. Vernon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/905f22d952_p975.png", school: "Mt. Zion" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8c5b1ac32d_p515.png", school: "Muchin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c2d88f8ac6_p412.png", school: "Mulberry Grove" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/82dc7dfd6b_p974.png", school: "Mundelein" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/93e08f44bd_p727.png", school: "Murphysboro" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/acae8488f7_p192.png", school: "Naperville C." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2bfd55c4a9_p545.png", school: "Naperville N." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/308025c697_p330.png", school: "Nashville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8165bbe7f8_p305.png", school: "Nazareth Aca." },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Near%20North%20Montessori%20School&primaryColor=&secondaryColor=",
    school: "NNMS",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5c2af335c7_p996.png", school: "Neoga" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/053c84ecc9_p198.png", school: "Neuqua Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5a03735ddb_p875.png", school: "New Athens" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ee6f9974bb_p87.png", school: "New Berlin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/defd90d494_p266.png", school: "New Trier Twp." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e5ddcc9a9f_p308.png", school: "Newark" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9fb6a77201_p371.png", school: "Newman Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/54a3042dd7_p321.png", school: "Newton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch3e27babc3e_p83.png", school: "Next Generation" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7c85a76811_p729.png", school: "Niles North" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/551c30397c_p547.png", school: "Niles West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6c82a76b22_p338.png", school: "Noble Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b5628e6937_p893.png", school: "Noble-Baker" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a7e9455ef4_p216.png", school: "Gary Comer" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c717225ef5_p605.png", school: "Nokomis" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/78453d778f_p892.png", school: "Normal Comm." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a2f061a08e_p723.png", school: "Normal West" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/be6c424fd7_p345.png", school: "NCOE" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/15c6175921_p421.png", school: "North Boone" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4b6aec1398_p825.png", school: "North Chicago" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4db0fbe45_p880.png", school: "North Clay" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/73381e5760_p890.png", school: "North Grand" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/42ba3080a3_p428.png", school: "North Greene" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/north-lawndale-college-prep-high-school-chicago-il_4039da50c8.png",
    school: "North Lawndale",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/02d46c9a03_p981.png", school: "North Love" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d06ab537a6_p60.png", school: "North Mac" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2885035b62_p168.png", school: "North Shore" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/73521d3649_p617.png", school: "Northridge Prep" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ed5cfef024_p393.png", school: "Northside Prep" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d139a21b97_p917.png", school: "Northwestern" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3732ff1c05_p514.png", school: "Niles" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cbf19b1d07_p709.png", school: "Notre Dame Peor" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0ecedffe82_p30.png", school: "Notre Dame" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ofallon-high-school-ofallon-il_4a08815eba.png", school: "O'Fallon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ef93e89f8e_p786.png", school: "Oak Forest" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9737219dc6_p951.png", school: "Oak Lawn" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/oak-park-and-river-forest-high-school-oak-park-il_c5d1c2d932.png",
    school: "OP-RF",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/338955ff56_p816.png", school: "Oakwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e5432933af_p837.png", school: "Oblong" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cddbe28616_p529.png", school: "Odin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5d3a7aec6b_p940.png", school: "Ogden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/216c47b5b2_p918.png", school: "Ohio" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9dcaee7f80_p336.png", school: "Okaw Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a870eb2fd0_p745.png", school: "Okawville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/olympia-high-school-stanford-il_34bb89a3c2.png", school: "Olympia" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/058b20e231_p401.png", school: "Orangeville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/822c28de1f_p749.png", school: "Oregon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a9775fad5c_p309.png", school: "Orion" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7c6122da3c_p501.png", school: "Orr" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/82a93b12cb_p394.png", school: "Oswego East" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0a6dd9dd4d_p185.png", school: "Oswego" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schf813666a14_p169.png", school: "Lourdes" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3fc58839a1_p487.png", school: "OLT" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/36b8c6ff5e_p476.png", school: "OLSHA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/284412af95_p485.png", school: "PORTA" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8d3cd733ef_p255.png", school: "Palatine" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fa5167753c_p801.png", school: "Palestine" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/5ef8dde74d_p90.png", school: "Pana" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/276ac0b983_p784.png", school: "Paris" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schddd91d822b_p449.png", school: "Parkview Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2a9bd2b9cf_p684.png", school: "Patoka" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cf3ed1eabf_p426.png", school: "Paw Paw" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch3a5802ccee_p36.png", school: "Paw Paw Jr" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/pawnee-high-school-pawnee-il_a3569bf6e4.png", school: "Pawnee" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3f84c18d1a_p505.png", school: "PBL" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d98eebd043_p915.png", school: "Seymour" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e3d2e8e18d_p51.png", school: "Pearl City" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8123fa0d09_p859.png", school: "Pecatonica" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/32bf2d2e31_p221.png", school: "Pekin" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/08db0c2c53_p420.png", school: "Peoria Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ca3120658b08410fadfaa27e619fbc4d.png", school: "Peoria Heights" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/123c86edb7_p366.png", school: "Peoria" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/peotone-high-school-peotone-il_26eae93c33.png", school: "Peotone" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e53098cbe5_p850.png", school: "PIITMS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/693565db5c_p386.png", school: "Perspectives" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/perspectivesjoslin-campus-chicago-il_2109e22fb4.png", school: "PJC" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/a740db096b_p516.png", school: "Phillips" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/phoenix-military-academy-chicago-il_28dbe16edf.png", school: "PMA" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/pinckneyville-high-school-pinckneyville-il_51b156931f.png",
    school: "Pinckneyville",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/747cde5017_p130.png", school: "Pittsfield" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7f427da597_p666.png", school: "Plainfield C." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/plainfield-east-high-school-plainfield-il_113ae302ae.png",
    school: "Plainfield East",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/75ff01108b_p721.png", school: "Plainfield N." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/plainfield-south-high-school-plainfield-il_7e928c4ef5.png",
    school: "Plainfield S.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/da4f8dee55_p879.png", school: "Plano" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/pleasant-hill-high-school-pleasant-hill-il_d76c860308.png",
    school: "Pleasant Hill",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c0c14edf86_p448.png", school: "Pleasant Plains" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/polo-high-school-polo-il_99cc64813b.png", school: "Polo" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_pontiac.png", school: "Pontiac" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/pope-county-high-school-golconda-il_1e2341d5d5.png",
    school: "Pope County",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/prairie-central-high-school-fairbury-il_a2da840a66.png",
    school: "Prairie Central",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b3cf4da12f_p994.png", school: "Prairie Ridge" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9e9f4477e1_p206.png", school: "Princeton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8c296d9b86_p810.png", school: "Princeville" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/pritzker-college-prep-high-school-chicago-il_5588cd8ddb.png",
    school: "Pritzker",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c31e43e38116487d8abbdc0f1c5241cc.png", school: "Pro Video" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Prologue%20High%20School&primaryColor=0x800000&secondaryColor=0xffd700",
    school: "Prologue",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/prophetstown-high-school-prophetstown-il_82ece30bf7.png",
    school: "Prophetstown",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/53f5b3e4a5_p996.png", school: "Prospect" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/prosser-career-academy-chicago-il_61dd10ddad.png", school: "Prosser" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4d8e6e032_p163.png", school: "Prov. Cath." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/28def5ade7_p785.png", school: "Prov. St. Mel" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/proviso-east-high-school-maywood-il_9f51f47c94.png",
    school: "Proviso East",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/proviso-west-high-school-hillside-il_d8885980ea.png",
    school: "Proviso West",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6b22a5165c_p278.png", school: "Putnam County" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/quad-cities-christian-school-moline-il_aca5da5a27.png",
    school: "Quad Cities",
  },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Queen%20of%20Peace%20High%20School&primaryColor=0x546376&secondaryColor=0xffffff",
    school: "Queen of Peace",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/98dc9c399f_p477.png", school: "Quest" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6e8c929e29_p881.png", school: "Quest Charter" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/quincy-christian-school-quincy-il_3f4b15532b.png",
    school: "Quincy Chr.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/816f120d3d_p45.png", school: "Quincy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/richwoods-high-school-peoria-il_71a6440ccf.png", school: "Richwoods" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Rickover%20Junior%20High%20School&primaryColor=&secondaryColor=",
    school: "Sauk Village",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rickover-naval-academy-chicago-il_84fca97313.png", school: "Rickover" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/409da530d8_p509.png", school: "Ridgeview" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/62d205709d_p515.png", school: "Ridgewood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/724cee7204_p318.png", school: "River Ridge" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=River%20of%20Life%20Christian%20School&primaryColor=&secondaryColor=",
    school: "River of Life",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/32c37927b5_p294.png", school: "Riverdale" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/46109471a3_p271.png", school: "R-B" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6e90c629ba_p19.png", school: "Riverton" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/roanokebenson-high-school-roanoke-il_2c10904e14.png",
    school: "Roanoke-Benson",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/roberto-clemente-community-academy-chicago-il_cef9c6626a.png",
    school: "Clemente",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/paul-robeson-high-school-chicago-il_34d8b29b72.png",
    school: "Robeson",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/11aaf40934_p142.png", school: "Robinson" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rochelle-high-school-rochelle-il_92c9f6147f.png", school: "Rochelle" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/62bdacbe8d_p507.png", school: "Rochelle Zell" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aa658ce573_p445.png", school: "Rochester" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rock-falls-high-school-rock-falls-il_0c4230ab18.png",
    school: "Rock Falls",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/55f493c5a5_p835.png", school: "Rock Island" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1496d00430_p257.png", school: "Rockford Auburn" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/39b25572c9_p167.png", school: "Rockford Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2f4b638a7e_p984.png", school: "Rockford East" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/rockford-lutheran-high-school-rockford-il_4e5eac34a2.png",
    school: "Rockford Luth.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ab815e15b6_p890.png", school: "Rockridge" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b667bb7557_p567.png", school: "Rolling Meadows" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2f4833c748_p445.png", school: "Romeoville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d3a5d7e481_p875.png", school: "Roosevelt" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f570ec7296_p844.png", school: "Rosary" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bc27f53028_p322.png", school: "Round Lake" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b4ef73f8e4_p256.png", school: "Routt" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/roweclark-math-science-academy-chicago-il_308a5f435c.png",
    school: "Rowe-Clark",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/roxana-high-school-roxana-il_c2a8f8f247.png", school: "Roxana" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/63677b8890_p750.png", school: "Roycemore" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/92fb56a115_p624.png", school: "R'ville-Ind." },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sacred-heartgriffin-high-school-springfield-il_47c66f2443.png",
    school: "SHG",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6d2c492de7_p921.png", school: "Saint Viator" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/9aa0b88c5d_p900.png", school: "Salem" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch3ccb5da643_p106.png", school: "Salt Fork" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7598be7a40_p258.png", school: "Sandoval" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/379635f7ec_p416.png", school: "Sandwich" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b66a370f35_p571.png", school: "Sangamon Valley" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/304b2457af_p685.png", school: "Goode STEM" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/44bc9460d9_p618.png", school: "Scales Mound" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4a45b90b8f_p775.png", school: "Schaumburg Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/cbe2d7f012_p840.png", school: "Schaumburg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b78051c308_p501.png", school: "Schlarman" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d26b98b3c3_p873.png", school: "Schurz" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/seneca-high-school-seneca-il_2bad797ed0.png", school: "Seneca" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=Seniors&primaryColor=&secondaryColor=", school: "Seniors" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/nicholas-senn-high-school-chicago-il_b74c559fbf.png", school: "Senn" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_serena.png", school: "Serena" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch5606fc72aa_p685.png", school: "Serena MS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0ee12159c2_p258.png", school: "Sesser-Valier" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Seton%20Academy&primaryColor=0x000000&secondaryColor=0xffd700",
    school: "Seton Academy",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/75e13e2c4b_p782.png", school: "Shawnee" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f3cf453c14_p464.png", school: "Shelbyville" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/shepard-high-school-palos-heights-il_5083112024.png",
    school: "Shepard",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/60a8e1c010_p373.png", school: "Sherrard" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/fec23f9912_p811.png", school: "Shiloh" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2c6bdf4e4c_p901.png", school: "Simeon" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b1da385ee7_p715.png", school: "Solorio Academy" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/97adce141a_p157.png", school: "Somonauk" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schab8ffe9ff9_p531.png", school: "Somonauk MS" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c67376bda2_p828.png", school: "South Beloit" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/41397147a6_p987.png", school: "South Central" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/e2e2750bbd_p358.png", school: "South Elgin" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/south-fork-high-school-kincaid-il_134c8064d1.png",
    school: "South Fork",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/aa656e2e6a_p246.png", school: "South Shore" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/7b1a41cf5b_p695.png", school: "SE Springfield" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/southeastern-high-school-augusta-il_43361f724c.png",
    school: "Southeastern",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch1474400e4f_p343.png", school: "SCPC" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/southland-college-preparatory-matteson-il_6f393fb73f.png",
    school: "Southland Prep",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/southwestern-high-school-piasa-il_752bb8d47e.png",
    school: "Southwestern",
  },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Sparland%20Midland%20Middle%20School&primaryColor=&secondaryColor=",
    school: "Sparland",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sparta-high-school-sparta-il_d3e134e038.png", school: "Sparta" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/spoon-river-valley-high-school-coop-w-cuba-london-mills-il_bb270e8a15.png",
    school: "SRV",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b9a69531df_p861.png", school: "Spry Community" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-anne-community-high-school-st-anne-il_a8e52ab0a1.png",
    school: "St. Anne",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch94a5ee212e_p415.png", school: "St Malachy" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=St%20Mary%27s%20School&primaryColor=&secondaryColor=",
    school: "St. Mary's",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/scha6622ae445_p575.png", school: "St Thomas" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=St%20Vincent%20de%20Paul%20Catholic%20School&primaryColor=&secondaryColor=",
    school: "St Vincent",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8606c002f1_p52.png", school: "St. Anthony" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/423e83cc72_p336.png", school: "St. Bede" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-benedict-high-school-chicago-il_a36ea3e1ed.png",
    school: "St. Benedict",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-charles-east-high-school-st-charles-il_58ab7862b8.png",
    school: "St. Charles E.",
  },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-charles-north-high-school-st-charles-il_ec656f65b5.png",
    school: "St. Charles N.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f5852ffa2e_p937.png", school: "St. Edward" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-elmo-high-school-st-elmo-il_71838c0fad.png", school: "St. Elmo" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-francis-high-school-wheaton-il_81d592c69d.png",
    school: "St. Francis",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/891b365161_p399.png", school: "SDS" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=St.%20Gregory%20High%20School&primaryColor=0xff0000&secondaryColor=0x0000ff%20%230020c2",
    school: "St. Gregory",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2ccd473889_p221.png", school: "St. Ignatius" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c27a79813a_p278.png", school: "St. Joseph" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-josephogden-high-school-st-joseph-il_1fd80adfe1.png",
    school: "SJO",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2b4e295bc2_p865.png", school: "St. Laurence" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d5e7053a58_p53.png", school: "St. Patrick" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/ac56466d1c_p533.png", school: "St. Rita" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/30a4bb6138_p704.png", school: "St. Scholastica" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1db5d1b2c1_p624.png", school: "St. Teresa" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/dd46ced3c01245ba838a472efea8db04.png", school: "Stagg" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0736da79a3_p778.png", school: "Stark County" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f345392cbf_p601.png", school: "Staunton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/6014d4cb7d_p666.png", school: "Steeleville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2f0dc769e3_p356.png", school: "Steinmetz" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/973e98dea4_p487.png", school: "Sterling Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2b22181095_p430.png", school: "Sterling" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/schc4282e4303_p195.png", school: "Sterling High" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/37ac71eaee_p414.png", school: "Stevenson" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/94b49f77f7_p327.png", school: "S-S" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/stillman-valley-high-school-stillman-valley-il_f0ab4b1d4e.png",
    school: "Stillman Valley",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/200717ca80_p275.png", school: "Stockton" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/2fa192d5cd_p494.png", school: "Streamwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/3a363649e2_p519.png", school: "Streator" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/0d9f41da90_p25.png", school: "Sullivan" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/sycamore-high-school-sycamore-il_501864ea09.png", school: "Sycamore" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/82f5d0955f_p549.png", school: "TCT" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/8d767be6c4_p948.png", school: "TEAM Englewood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/73df93e305_p555.png", school: "Taft" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/336ecbf9f9_p187.png", school: "Taylorville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b053586182_p771.png", school: "Teutopolis" },
  { src: "https://font-logo.nfhsnetwork.com/logo?name=The%20Ancona%20School&primaryColor=&secondaryColor=", school: "TAS" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/the-high-school-of-saint-thomas-more-champaign-st-thomas-more-champaign-il_1fab3be539.png",
    school: "St. Thomas More",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f58cc18584_p145.png", school: "Willows Academy" },
  {
    src: "https://font-logo.nfhsnetwork.com/logo?name=Thomasboro%20Grade%20School&primaryColor=&secondaryColor=",
    school: "Thomasboro",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/4ad61a5d21_p721.png", school: "Thompsonville" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f7053354c3_p297.png", school: "Thornridge" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/b7dd9b6c91_p724.png", school: "TFN" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/abf45e7e00_p161.png", school: "TFS" },
  {
    src: "https://cfunity-school-logos.nfhsnetwork.com/v1/thornton-township-high-school-harvey-il_f0a9e65fb3.png",
    school: "Thornton Twp.",
  },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/98e9c84b9e_p690.png", school: "Thornwood" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/f0767c0473_p672.png", school: "Tilden" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/1a251ab712_p770.png", school: "Timothy Chr." },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/bda362bd73_p703.png", school: "Tinley Park" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/c5afc23630_p83.png", school: "Tremont" },
  { src: "https://cfunity-school-logos.nfhsnetwork.com/v1/d355957859_p915.png", school: "Tri-City" },
];
