export default schoolLogos = [
  { school: "Wheeling High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/il_logo_wheeling2.png" },
  { school: "Latin School of Chicago", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/9cbc05bf67_p337.png" },
  { school: "Dundee-Crown High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/a04dc4b424_p667.png" },
  { school: "Northridge Prep High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/73521d3649_p617.png" },
  { school: "Waukegan High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/763ca3b411_p30.png" },
  {
    school: "Carmel Catholic High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/carmel-catholic-high-school-mundelein-il_2c4eec5890.png",
  },
  {
    school: "Warren Township High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/warren-high-school-gurnee-gurnee-il_9838b4e54f.png",
  },
  { school: "DePaul College Prep", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/c898b615a1_p139.png" },
  { school: "Rochelle Zell Jewish High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/62bdacbe8d_p507.png" },
  { school: "Stevenson High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/ee7ed91cd1_p115.png" },
  { school: "St. Ignatius College Prep", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/2ccd473889_p221.png" },
  { school: "North Shore Country Day School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/2885035b62_p168.png" },
  {
    school: "Walter Payton College Prep High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/walter-payton-college-prep-high-school-chicago-il_48a5fdaa90.png",
  },
  { school: "University High School", url: "https://cfunity-state-association-logos.nfhsnetwork.com/uil.png" },
  { school: "St. Viator High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch1797dd0e86_p200.png" },
  { school: "The Willows Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/f58cc18584_p145.png" },
  { school: "Evanston Township High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/aff92fd52f_p190.png" },
  { school: "Elgin Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/c7d0840c06_p667.png" },
  {
    school: "Regina Dominican High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/regina-dominican-high-school-wilmette-il_0b6ddbbbfa.png",
  },
  { school: "Antioch High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/tn_logo_antioch.png" },
  { school: "Beacon Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/sche2fb092c52_p373.png" },
  { school: "Grant High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/889f7f0a56_p613.png" },
  { school: "Lake Forest High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/4377581764_p519.png" },
  { school: "Deerfield High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/963f96f4b5_p353.png" },
  { school: "Morgan Park Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/a5e44dc0d7_p368.png" },
  { school: "Woodlands Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/d6783f1406_p837.png" },
  {
    school: "Highland Park High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/highland-park-high-school-highland-park-il_8fca70e17e.png",
  },
  { school: "Waukegan High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/763ca3b411_p30.png" },
  { school: "Zion-Benton High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/724cf852f6_p917.png" },
  {
    school: "Highland Park High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/highland-park-high-school-highland-park-il_8fca70e17e.png",
  },
  { school: "Maine East High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/2a03ea8382_p536.png" },
  { school: "Naperville North High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/2bfd55c4a9_p545.png" },
  { school: "Francis Parker School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/631182d73e_p886.png" },
  {
    school: "Oak Park & River Forest High School",
    url: "https://stats.digitalscout.com/img/logos/schools/581457695f9645a5b4b03c7e1f6f4024.png",
  },
  {
    school: "F.W. Parker High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/fw-parker-high-school-chicago-il_f1ef3f8c70.png",
  },
  {
    school: "Grayslake North High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/grayslake-north-high-school-grayslake-il_13f5f0cbfd.png",
  },
  { school: "Joliet Central HS", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/38d54b9f16_p251.png" },
  { school: "Mundelein High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/82dc7dfd6b_p974.png" },
  {
    school: "Glenbard West High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/glenbard-west-high-school-glen-ellyn-il_b9ef024c73.png",
  },
  { school: "Ridgewood High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/cbed8562e2_p805.png" },
  {
    school: "Glenbrook South High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/c3c9137e8a064860bd3257655c44d1f9.png",
  },
  { school: "Westlake Christian Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/69a87dd155_p609.png" },
  {
    school: "St Francis HS-Wheaton",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/st-francis-high-school-wheaton-il_81d592c69d.png",
  },
  { school: "Rockford Christian Schools", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/39b25572c9_p167.png" },
  { school: "Glenwood HS", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/a6644b3db3_p675.png" },
  { school: "Moline High", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/9e598f0572_p367.png" },
  { school: "Newark High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/03630a903a_p531.png" },
  { school: "Morton HS", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/5cbd10860d_p515.png" },
  { school: "Conant High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/nh_logo_conant.png" },
  {
    school: "Resurrection High School",
    url: "https://cfunity-school-logos.nfhsnetwork.com/v1/resurrection-high-school-chicago-il_1504c32d81.png",
  },
  { school: "HRK Eagles", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/f4b1d81b67_p460.png" },
  { school: "Niles North High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/7c85a76811_p729.png" },
  { school: "Rufus King High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/668c064224_p465.png" },
  { school: "Rice Memorial High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/4fd46237ec_p613.png" },
  { school: "Vernon Hills High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/8280179b24_p762.png" },
  { school: "Livonia Stevenson HS", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/150496796d_p525.png" },
  { school: "North Chicago High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/4b6aec1398_p825.png" },
  { school: "Peddie School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/691cef62b6_p733.png" },
  { school: "Yorkville Christian School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/sch0b8b1ed6e5_p625.png" },
  { school: "La Lumiere School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/87477c256e_p812.png" },
  { school: "Woodstock High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/9b386a0c54_p492.png" },
  { school: "Harvard High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/9c2791faba_p597.png" },
  { school: "Jefferson High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/9280a50024_p504.png" },
  { school: "Brother Rice High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/30eba8eb46_p47.png" },
  { school: "Harlem High School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/edc3c0e0f0_p991.png" },
  { school: "Notre Dame Academy", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/5d7acc82f9_p827.png" },
  { school: "La Lumiere School", url: "https://cfunity-school-logos.nfhsnetwork.com/v1/87477c256e_p812.png" },
];
