exports.schools = [
  "Wheeling High School",
  "Latin School of Chicago",
  "Dundee-Crown High School",
  "Northridge Prep High School",
  "Waukegan High School",
  "Carmel Catholic High School",
  "Warren Township High School",
  "DePaul College Prep",
  "Rochelle Zell Jewish High School",
  "Stevenson High School",
  "St. Ignatius College Prep",
  "North Shore Country Day School",
  "Walter Payton College Prep High School",
  "University High School",
  "St. Viator High School",
  "The Willows Academy",
  "Evanston Township High School",
  "Elgin Academy",
  "Regina Dominican High School",
  "Antioch High School",
  "Beacon Academy",
  "Grant High School",
  "Lake Forest High School",
  "Deerfield High School",
  "Morgan Park Academy",
  "Woodlands Academy",
  "Highland Park High School",
  "Waukegan High School",
  "Zion-Benton High School",
  "Highland Park High School",
  "Maine East High School",
  "Naperville North High School",
  "Ridley College",
  "Francis Parker School",
  "Oak Park & River Forest High School",
  "Grayslake North High School",
  "Joliet Central HS",
  "Mundelein High School",
  "Glenbard West High School",
  "Ridgewood High School",
  "Glenbrook South High School",
  "Blyth Academy",
  "Westlake Christian Academy",
  "St Francis HS-Wheaton",
  "Rockford Christian Schools",
  "Glenwood HS",
  "Moline High",
  "Durand Jr/Sr High School",
  "Newark High School",
  "Morton HS",
  "Conant High School",
  "Chesterton Academy of Immaculate Heart",
  "Resurrection High School",
  "HRK Eagles",
  "Niles North High School",
  "Rufus King High School",
  "Rice Memorial High School",
  "Vernon Hills High School",
  "Livonia Stevenson HS",
  "North Chicago High School",
  "Peddie School",
  "Yorkville Christian School",
  "Milwaukee Admirals Hockey Club",
  "La Lumiere School",
  "Woodstock High School",
  "Harvard High School",
  "Jefferson High School",
  "Round Lake Senior High School",
  "Brother Rice High School",
  "Catholic Central High School-Redford",
  "Harlem High School",
  "Notre Dame Academy",
  "La Lumiere School",
];
